import { Restaurant, Review, Booking } from './types';

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Casa Verde',
    cuisine: 'Mexican',
    description: 'Authentic Mexican cuisine with a modern twist. Experience the vibrant flavors of Mexico in an elegant setting.',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    address: '123 Sunset Blvd, Los Angeles, CA 90028',
    phone: '+1 (310) 555-0101',
    priceRange: '$$$',
    rating: 4.7,
    reviewCount: 234,
    openTime: '11:00',
    closeTime: '23:00',
    tables: [
      { id: 't1', name: 'Window Seat A', location: 'window', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Window Seat B', location: 'window', capacity: 2, floor: 'Ground' },
      { id: 't3', name: 'Main Hall 1', location: 'main hall', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Main Hall 2', location: 'main hall', capacity: 4, floor: 'Ground' },
      { id: 't5', name: 'Patio 1', location: 'outdoor patio', capacity: 6, floor: 'Ground' },
      { id: 't6', name: 'Private Room', location: 'private room', capacity: 8, floor: 'First' },
      { id: 't7', name: 'Bar Area 1', location: 'bar area', capacity: 2, floor: 'Ground' },
      { id: 't8', name: 'Balcony 1', location: 'balcony', capacity: 4, floor: 'First' },
    ],
    availableSlots: ['12:00', '12:30', '13:00', '13:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00'],
    tags: ['Mexican', 'Cocktails', 'Date Night', 'Group Friendly'],
  },
  {
    id: '2',
    name: 'Sakura Garden',
    cuisine: 'Japanese',
    description: 'A serene Japanese dining experience featuring omakase menus and traditional kaiseki cuisine.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    address: '456 Cherry Blossom Ave, San Francisco, CA 94102',
    phone: '+1 (415) 555-0202',
    priceRange: '$$$$',
    rating: 4.9,
    reviewCount: 187,
    openTime: '12:00',
    closeTime: '22:00',
    tables: [
      { id: 't1', name: 'Sushi Bar 1', location: 'sushi bar', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Sushi Bar 2', location: 'sushi bar', capacity: 2, floor: 'Ground' },
      { id: 't3', name: 'Garden View 1', location: 'garden view', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Garden View 2', location: 'garden view', capacity: 4, floor: 'Ground' },
      { id: 't5', name: 'Tatami Room', location: 'tatami room', capacity: 6, floor: 'Ground' },
      { id: 't6', name: 'Private Booth 1', location: 'private booth', capacity: 4, floor: 'First' },
    ],
    availableSlots: ['12:00', '13:00', '14:00', '18:00', '19:00', '20:00', '21:00'],
    tags: ['Japanese', 'Sushi', 'Omakase', 'Fine Dining'],
  },
  {
    id: '3',
    name: 'La Bella Italia',
    cuisine: 'Italian',
    description: 'Traditional Italian recipes passed down through generations. Homemade pasta and wood-fired pizzas.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    address: '789 Olive Street, New York, NY 10001',
    phone: '+1 (212) 555-0303',
    priceRange: '$$$',
    rating: 4.5,
    reviewCount: 312,
    openTime: '11:30',
    closeTime: '23:30',
    tables: [
      { id: 't1', name: 'Terrace A', location: 'outdoor terrace', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Terrace B', location: 'outdoor terrace', capacity: 4, floor: 'Ground' },
      { id: 't3', name: 'Main Dining 1', location: 'main dining', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Main Dining 2', location: 'main dining', capacity: 6, floor: 'Ground' },
      { id: 't5', name: 'Wine Cellar', location: 'wine cellar', capacity: 8, floor: 'Basement' },
      { id: 't6', name: 'Chef Table', location: 'chef table', capacity: 2, floor: 'Ground' },
    ],
    availableSlots: ['11:30', '12:00', '12:30', '13:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '21:00', '21:30'],
    tags: ['Italian', 'Pizza', 'Pasta', 'Wine Bar'],
  },
  {
    id: '4',
    name: 'The Golden Fork',
    cuisine: 'American',
    description: 'Contemporary American cuisine showcasing locally sourced ingredients and seasonal menus.',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    address: '321 Heritage Way, Chicago, IL 60601',
    phone: '+1 (312) 555-0404',
    priceRange: '$$$',
    rating: 4.6,
    reviewCount: 445,
    openTime: '11:00',
    closeTime: '22:00',
    tables: [
      { id: 't1', name: 'Street View 1', location: 'street view', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Street View 2', location: 'street view', capacity: 4, floor: 'Ground' },
      { id: 't3', name: 'Central Hall A', location: 'central hall', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Central Hall B', location: 'central hall', capacity: 6, floor: 'Ground' },
      { id: 't5', name: 'Lounge 1', location: 'lounge', capacity: 4, floor: 'First' },
      { id: 't6', name: 'Rooftop 1', location: 'rooftop', capacity: 6, floor: 'Roof' },
      { id: 't7', name: 'Rooftop 2', location: 'rooftop', capacity: 4, floor: 'Roof' },
    ],
    availableSlots: ['11:00', '11:30', '12:00', '12:30', '13:00', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30'],
    tags: ['American', 'Farm-to-Table', 'Craft Cocktails', 'Brunch'],
  },
  {
    id: '5',
    name: 'Spice Route',
    cuisine: 'Indian',
    description: 'An aromatic journey through India with authentic tandoor dishes and rich curries.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
    address: '567 Curry Lane, Houston, TX 77001',
    phone: '+1 (713) 555-0505',
    priceRange: '$$',
    rating: 4.4,
    reviewCount: 298,
    openTime: '12:00',
    closeTime: '23:00',
    tables: [
      { id: 't1', name: 'Front Window 1', location: 'front window', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Main Area 1', location: 'main area', capacity: 4, floor: 'Ground' },
      { id: 't3', name: 'Main Area 2', location: 'main area', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Booth 1', location: 'booth', capacity: 4, floor: 'Ground' },
      { id: 't5', name: 'Private Dining', location: 'private dining', capacity: 10, floor: 'First' },
    ],
    availableSlots: ['12:00', '12:30', '13:00', '13:30', '18:00', '18:30', '19:00', '19:30', '20:00', '20:30', '21:00', '21:30', '22:00'],
    tags: ['Indian', 'Vegetarian Friendly', 'Spicy', 'Halal'],
  },
  {
    id: '6',
    name: 'Le Petit Bistro',
    cuisine: 'French',
    description: 'Classic French bistro serving traditional dishes with Parisian charm and elegance.',
    image: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
    address: '890 Eiffel Ct, Miami, FL 33101',
    phone: '+1 (305) 555-0606',
    priceRange: '$$$$',
    rating: 4.8,
    reviewCount: 156,
    openTime: '12:00',
    closeTime: '22:30',
    tables: [
      { id: 't1', name: 'Boulevard View 1', location: 'boulevard view', capacity: 2, floor: 'Ground' },
      { id: 't2', name: 'Boulevard View 2', location: 'boulevard view', capacity: 2, floor: 'Ground' },
      { id: 't3', name: 'Interior A', location: 'interior', capacity: 4, floor: 'Ground' },
      { id: 't4', name: 'Interior B', location: 'interior', capacity: 4, floor: 'Ground' },
      { id: 't5', name: 'Cellar Room', location: 'cellar', capacity: 6, floor: 'Basement' },
    ],
    availableSlots: ['12:00', '13:00', '14:00', '19:00', '19:30', '20:00', '20:30', '21:00'],
    tags: ['French', 'Wine', 'Romantic', 'Fine Dining'],
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    restaurantId: '1',
    userId: 'u1',
    userName: 'Sarah M.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 5,
    comment: 'Absolutely amazing food! The tacos al pastor were out of this world. Will definitely come back!',
    date: '2024-06-15',
    visitDate: '2024-06-14',
  },
  {
    id: 'r2',
    restaurantId: '1',
    userId: 'u2',
    userName: 'John D.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 4,
    comment: 'Great atmosphere and delicious margaritas. The guacamole is freshly made tableside.',
    date: '2024-06-10',
    visitDate: '2024-06-09',
  },
  {
    id: 'r3',
    restaurantId: '1',
    userId: 'u3',
    userName: 'Emma L.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 5,
    comment: 'Perfect for date night. The staff was incredibly attentive and the food was exceptional.',
    date: '2024-06-05',
    visitDate: '2024-06-04',
  },
  {
    id: 'r4',
    restaurantId: '2',
    userId: 'u4',
    userName: 'Michael K.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 5,
    comment: "The omakase experience was transcendent. Chef Tanaka's craftsmanship is unparalleled.",
    date: '2024-06-12',
    visitDate: '2024-06-11',
  },
  {
    id: 'r5',
    restaurantId: '2',
    userId: 'u5',
    userName: 'Yuki T.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 5,
    comment: 'Authentic Japanese flavors. The tatami room is perfect for a special occasion.',
    date: '2024-06-08',
    visitDate: '2024-06-07',
  },
  {
    id: 'r6',
    restaurantId: '3',
    userId: 'u6',
    userName: 'Marco R.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 4,
    comment: 'Nonna would approve! The homemade pasta is divine and reminds me of home.',
    date: '2024-06-14',
    visitDate: '2024-06-13',
  },
  {
    id: 'r7',
    restaurantId: '4',
    userId: 'u7',
    userName: 'Ashley B.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 5,
    comment: 'The farm-to-table concept really shines through. Fresh, seasonal ingredients make every dish special.',
    date: '2024-06-11',
    visitDate: '2024-06-10',
  },
  {
    id: 'r8',
    restaurantId: '5',
    userId: 'u8',
    userName: 'Priya S.',
    userAvatar: 'https://via.placeholder.com/40',
    rating: 4,
    comment: 'Authentic Indian flavors. The biryani is exceptional and the staff accommodated my dietary needs perfectly.',
    date: '2024-06-09',
    visitDate: '2024-06-08',
  },
];

export const SAMPLE_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    restaurantId: '1',
    userId: 'demo-user',
    userName: 'Demo User',
    userEmail: 'demo@maiz.com',
    userPhone: '+1 555-0100',
    tableId: 't3',
    tableName: 'Main Hall 1',
    tableLocation: 'main hall',
    date: new Date().toISOString().split('T')[0],
    time: '19:00',
    duration: 90,
    partySize: 4,
    status: 'confirmed',
    allergies: ['nuts', 'gluten'],
    specialRequests: 'Anniversary dinner, please prepare a small cake.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b2',
    restaurantId: '1',
    userId: 'demo-user-2',
    userName: 'Jane Smith',
    userEmail: 'jane@example.com',
    userPhone: '+1 555-0101',
    tableId: 't5',
    tableName: 'Patio 1',
    tableLocation: 'outdoor patio',
    date: new Date().toISOString().split('T')[0],
    time: '20:00',
    duration: 90,
    partySize: 6,
    status: 'confirmed',
    allergies: ['dairy'],
    specialRequests: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b3',
    restaurantId: '1',
    userId: 'demo-user-3',
    userName: 'Bob Johnson',
    userEmail: 'bob@example.com',
    userPhone: '+1 555-0102',
    tableId: 't1',
    tableName: 'Window Seat A',
    tableLocation: 'window',
    date: new Date().toISOString().split('T')[0],
    time: '18:30',
    duration: 90,
    partySize: 2,
    status: 'confirmed',
    allergies: [],
    specialRequests: 'Prefer a quiet corner if possible.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'b4',
    restaurantId: '1',
    userId: 'demo-user-4',
    userName: 'Alice Brown',
    userEmail: 'alice@example.com',
    userPhone: '+1 555-0103',
    tableId: 't6',
    tableName: 'Private Room',
    tableLocation: 'private room',
    date: new Date().toISOString().split('T')[0],
    time: '19:30',
    duration: 120,
    partySize: 8,
    status: 'confirmed',
    allergies: ['shellfish', 'peanuts'],
    specialRequests: 'Corporate dinner, please set up presentation screen.',
    createdAt: new Date().toISOString(),
  },
];
